/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author Jberdugo
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Jpanel_componentes = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Jpanel_perfiericos = new javax.swing.JPanel();
        txt_idpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_fabripf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_modelopf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_preciopf = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cbx_tipocon_pf = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbx_tipopf = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable_pf = new javax.swing.JTable();
        btn_aggpf = new javax.swing.JButton();
        btn_editarpf = new javax.swing.JButton();
        btn_deletepf = new javax.swing.JButton();
        btn_freshpf = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txt_nomp = new javax.swing.JTextField();
        Jpanel_unidadc = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_idcpu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_fabricpu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_modelocpu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_preciocpu = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txt_proces_cpu = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbx_discocpu = new javax.swing.JComboBox<>();
        btn_remov_cpu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtable_cpu = new javax.swing.JTable();
        btn_editarcpu = new javax.swing.JButton();
        btn_aggcpu = new javax.swing.JButton();
        btn_fresh_cpu = new javax.swing.JButton();
        Jpanel_admin = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_idcpu_pc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_idpf_pc = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtext_dtcpu = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtext_dtpf = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtext_dtpc = new javax.swing.JTextArea();
        btn_buscaridpf = new javax.swing.JButton();
        btn_limpiar_txtpc = new javax.swing.JButton();
        btn_proc_venta = new javax.swing.JButton();
        lbl_total_compra = new javax.swing.JLabel();
        btn_buscaridcpu = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        Jpanel_ventas = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        lbl_subtotfin = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Jtext_dtventa = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        txt_modiprecio = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_totalfin = new javax.swing.JLabel();
        btn_impf = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txt_montopago = new javax.swing.JTextField();
        btn_pagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MVC");

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Jpanel_componentes.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 255));

        Jpanel_perfiericos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel4.setText("NOMBRE FABRICANTE:");

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel5.setText("MODELO:");

        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel6.setText("PRECIO VENTA:");

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel7.setText("SELECCIONE TIPO:");

        cbx_tipocon_pf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USB-C", "USB 3.0", "LIGHTING", "USB 5.0" }));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel8.setText("TIPO DE CONECTOR:");

        cbx_tipopf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TECLADO", "MOUSE", "TABLETA GRAFICA", "LAPIZ OPTICO", "PANTALLA", "PARLANTE", "LAPIZ OPTICO", "IMPRESORA INYECCION", "IMPRESORA LASER", "PANTALLA TACTIL" }));

        Jtable_pf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PF", "NOMBRE PF.", "MODELO", "PRECIO PF.", "TIPO PF.", "CONECTOR", "FABRICANTE"
            }
        ));
        jScrollPane1.setViewportView(Jtable_pf);

        btn_aggpf.setBackground(new java.awt.Color(204, 204, 255));
        btn_aggpf.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btn_aggpf.setForeground(new java.awt.Color(0, 153, 204));
        btn_aggpf.setText("AÑADIR PERIFERICO");

        btn_editarpf.setBackground(new java.awt.Color(204, 204, 255));
        btn_editarpf.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btn_editarpf.setForeground(new java.awt.Color(0, 153, 204));
        btn_editarpf.setText("EDITAR");

        btn_deletepf.setBackground(new java.awt.Color(204, 204, 255));
        btn_deletepf.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btn_deletepf.setForeground(new java.awt.Color(0, 153, 204));
        btn_deletepf.setText("ELIMINAR");

        btn_freshpf.setBackground(new java.awt.Color(204, 204, 255));
        btn_freshpf.setFont(new java.awt.Font("Roboto Black", 1, 10)); // NOI18N
        btn_freshpf.setForeground(new java.awt.Color(0, 153, 204));
        btn_freshpf.setText("LISTAR");

        jLabel22.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel22.setText("nombre:");

        javax.swing.GroupLayout Jpanel_perfiericosLayout = new javax.swing.GroupLayout(Jpanel_perfiericos);
        Jpanel_perfiericos.setLayout(Jpanel_perfiericosLayout);
        Jpanel_perfiericosLayout.setHorizontalGroup(
            Jpanel_perfiericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_perfiericosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Jpanel_perfiericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_perfiericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(txt_modelopf)
                        .addComponent(txt_fabripf)
                        .addComponent(jLabel4)
                        .addComponent(txt_preciopf)
                        .addComponent(cbx_tipocon_pf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbx_tipopf, 0, 0, Short.MAX_VALUE)
                        .addGroup(Jpanel_perfiericosLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_idpf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Jpanel_perfiericosLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nomp, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(Jpanel_perfiericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_perfiericosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_perfiericosLayout.createSequentialGroup()
                        .addComponent(btn_aggpf, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editarpf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_deletepf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btn_freshpf)
                        .addGap(8, 8, 8))))
        );
        Jpanel_perfiericosLayout.setVerticalGroup(
            Jpanel_perfiericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_perfiericosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel_perfiericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Jpanel_perfiericosLayout.createSequentialGroup()
                        .addGroup(Jpanel_perfiericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(Jpanel_perfiericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fabripf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_modelopf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_preciopf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_tipopf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Jpanel_perfiericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_tipocon_pf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deletepf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editarpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aggpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_freshpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PERIFERICOS", Jpanel_perfiericos);

        Jpanel_unidadc.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel9.setText("ID:");

        jLabel10.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel10.setText("NOMBRE FABRICANTE:");

        jLabel11.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel11.setText("MODELO:");

        jLabel12.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel12.setText("PRECIO VENTA:");

        jLabel13.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel13.setText("PROCESADOR:");

        jLabel14.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel14.setText("DISCO:");

        cbx_discocpu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SSD", "MECANICA" }));

        btn_remov_cpu.setBackground(new java.awt.Color(204, 204, 255));
        btn_remov_cpu.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btn_remov_cpu.setForeground(new java.awt.Color(0, 153, 204));
        btn_remov_cpu.setText("ELIMINAR");

        Jtable_cpu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID CPU", "NOMBRE F.", "MODELO", "PRECIO CPU", "PROCESADOR", "DISCO"
            }
        ));
        jScrollPane2.setViewportView(Jtable_cpu);

        btn_editarcpu.setBackground(new java.awt.Color(204, 204, 255));
        btn_editarcpu.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btn_editarcpu.setForeground(new java.awt.Color(0, 153, 204));
        btn_editarcpu.setText("EDITAR");

        btn_aggcpu.setBackground(new java.awt.Color(204, 204, 255));
        btn_aggcpu.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btn_aggcpu.setForeground(new java.awt.Color(0, 153, 204));
        btn_aggcpu.setText("AÑADIR CPU");

        btn_fresh_cpu.setBackground(new java.awt.Color(204, 204, 255));
        btn_fresh_cpu.setFont(new java.awt.Font("Roboto Black", 1, 10)); // NOI18N
        btn_fresh_cpu.setForeground(new java.awt.Color(0, 153, 204));
        btn_fresh_cpu.setText("LISTAR");
        btn_fresh_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fresh_cpuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jpanel_unidadcLayout = new javax.swing.GroupLayout(Jpanel_unidadc);
        Jpanel_unidadc.setLayout(Jpanel_unidadcLayout);
        Jpanel_unidadcLayout.setHorizontalGroup(
            Jpanel_unidadcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_unidadcLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(Jpanel_unidadcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jSeparator5)
                    .addComponent(txt_idcpu)
                    .addComponent(jLabel9)
                    .addComponent(txt_modelocpu)
                    .addComponent(txt_fabricpu)
                    .addComponent(jLabel10)
                    .addComponent(txt_preciocpu)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txt_proces_cpu)
                    .addComponent(cbx_discocpu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(Jpanel_unidadcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(Jpanel_unidadcLayout.createSequentialGroup()
                        .addComponent(btn_aggcpu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_editarcpu, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_remov_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(btn_fresh_cpu)))
                .addContainerGap())
        );
        Jpanel_unidadcLayout.setVerticalGroup(
            Jpanel_unidadcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_unidadcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel_unidadcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_unidadcLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_idcpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fabricpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_modelocpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_preciocpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_proces_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel_unidadcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_unidadcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_aggcpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_editarcpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_remov_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_fresh_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbx_discocpu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CPU (unidad central)", Jpanel_unidadc);

        javax.swing.GroupLayout Jpanel_componentesLayout = new javax.swing.GroupLayout(Jpanel_componentes);
        Jpanel_componentes.setLayout(Jpanel_componentesLayout);
        Jpanel_componentesLayout.setHorizontalGroup(
            Jpanel_componentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
            .addGroup(Jpanel_componentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );
        Jpanel_componentesLayout.setVerticalGroup(
            Jpanel_componentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
            .addGroup(Jpanel_componentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_componentesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );

        jTabbedPane2.addTab("COMPONENTES", Jpanel_componentes);

        Jpanel_admin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel15.setText("ARMAR COMPUTADOR:");

        jLabel16.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel16.setText("DIGITE ID DEL PERIFERICO:");

        jLabel17.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel17.setText("DIGITE ID DE LA CPU:");

        jtext_dtcpu.setEditable(false);
        jtext_dtcpu.setColumns(20);
        jtext_dtcpu.setRows(5);
        jScrollPane3.setViewportView(jtext_dtcpu);

        jtext_dtpf.setEditable(false);
        jtext_dtpf.setColumns(20);
        jtext_dtpf.setRows(5);
        jtext_dtpf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jtext_dtpf);

        jLabel18.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel18.setText("DETALLES:");

        jLabel19.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jLabel19.setText("DETALLES:");

        jLabel20.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel20.setText("DETALLES COMPUTADOR:");

        jtext_dtpc.setColumns(20);
        jtext_dtpc.setRows(5);
        jScrollPane5.setViewportView(jtext_dtpc);

        btn_buscaridpf.setBackground(new java.awt.Color(204, 204, 255));
        btn_buscaridpf.setFont(new java.awt.Font("Roboto Black", 1, 10)); // NOI18N
        btn_buscaridpf.setForeground(new java.awt.Color(0, 153, 204));
        btn_buscaridpf.setText("AGREGAR");

        btn_limpiar_txtpc.setBackground(new java.awt.Color(204, 204, 255));
        btn_limpiar_txtpc.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btn_limpiar_txtpc.setForeground(new java.awt.Color(0, 153, 204));
        btn_limpiar_txtpc.setText("LIMPIAR");

        btn_proc_venta.setBackground(new java.awt.Color(204, 204, 255));
        btn_proc_venta.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btn_proc_venta.setForeground(new java.awt.Color(0, 153, 204));
        btn_proc_venta.setText("PROCEDER A VENTA");

        lbl_total_compra.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lbl_total_compra.setText("0");

        btn_buscaridcpu.setBackground(new java.awt.Color(204, 204, 255));
        btn_buscaridcpu.setFont(new java.awt.Font("Roboto Black", 1, 10)); // NOI18N
        btn_buscaridcpu.setForeground(new java.awt.Color(0, 153, 204));
        btn_buscaridcpu.setText("AGREGAR");

        jLabel27.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel27.setText("TOTAL:");

        javax.swing.GroupLayout Jpanel_adminLayout = new javax.swing.GroupLayout(Jpanel_admin);
        Jpanel_admin.setLayout(Jpanel_adminLayout);
        Jpanel_adminLayout.setHorizontalGroup(
            Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_adminLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(72, 72, 72))
            .addGroup(Jpanel_adminLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_adminLayout.createSequentialGroup()
                        .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_idpf_pc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscaridpf, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addComponent(jScrollPane4)
                    .addGroup(Jpanel_adminLayout.createSequentialGroup()
                        .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_adminLayout.createSequentialGroup()
                        .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3)
                                .addComponent(jSeparator7))
                            .addGroup(Jpanel_adminLayout.createSequentialGroup()
                                .addComponent(txt_idcpu_pc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_buscaridcpu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Jpanel_adminLayout.createSequentialGroup()
                                .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(btn_limpiar_txtpc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Jpanel_adminLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_proc_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(Jpanel_adminLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(lbl_total_compra))))))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        Jpanel_adminLayout.setVerticalGroup(
            Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_adminLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_adminLayout.createSequentialGroup()
                        .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_idcpu_pc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idpf_pc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscaridpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscaridcpu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel_adminLayout.createSequentialGroup()
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(Jpanel_adminLayout.createSequentialGroup()
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Jpanel_adminLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_total_compra)
                            .addComponent(jLabel27))))
                .addGap(18, 18, 18)
                .addGroup(Jpanel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpiar_txtpc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_proc_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("ADMINISTRACION", Jpanel_admin);

        Jpanel_ventas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 255, 0));
        jLabel21.setText("SUBTOTAL:");

        lbl_subtotfin.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lbl_subtotfin.setText("0");

        jLabel23.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel23.setText("DETALLE VENTA:");

        Jtext_dtventa.setColumns(20);
        Jtext_dtventa.setRows(5);
        jScrollPane6.setViewportView(Jtext_dtventa);

        jLabel24.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel24.setText("MODIFICAR PRECIO:");

        jLabel25.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel25.setText("TOTAL: ");

        txt_totalfin.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        txt_totalfin.setText("0");

        btn_impf.setBackground(new java.awt.Color(204, 204, 255));
        btn_impf.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        btn_impf.setForeground(new java.awt.Color(0, 153, 204));
        btn_impf.setText("IMPRIMIR FACTURA");

        jLabel26.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel26.setText("MONTO PAGADO:");

        btn_pagar.setBackground(new java.awt.Color(204, 204, 255));
        btn_pagar.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        btn_pagar.setForeground(new java.awt.Color(0, 153, 204));
        btn_pagar.setText("PAGAR");

        javax.swing.GroupLayout Jpanel_ventasLayout = new javax.swing.GroupLayout(Jpanel_ventas);
        Jpanel_ventas.setLayout(Jpanel_ventasLayout);
        Jpanel_ventasLayout.setHorizontalGroup(
            Jpanel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_ventasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Jpanel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Jpanel_ventasLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addGap(18, 18, 18)
                            .addComponent(lbl_subtotfin))
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_modiprecio)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Jpanel_ventasLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(txt_totalfin))
                    .addGroup(Jpanel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_montopago, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(Jpanel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_ventasLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_ventasLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(240, 240, 240))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_ventasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_impf, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(Jpanel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Jpanel_ventasLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btn_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(680, Short.MAX_VALUE)))
        );
        Jpanel_ventasLayout.setVerticalGroup(
            Jpanel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_ventasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Jpanel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lbl_subtotfin)
                    .addComponent(jLabel23))
                .addGroup(Jpanel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_ventasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_modiprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_totalfin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_montopago, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(130, Short.MAX_VALUE))
                    .addGroup(Jpanel_ventasLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane6)
                        .addGap(18, 18, 18)
                        .addComponent(btn_impf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(Jpanel_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_ventasLayout.createSequentialGroup()
                    .addContainerGap(414, Short.MAX_VALUE)
                    .addComponent(btn_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)))
        );

        jTabbedPane2.addTab("VENTA", Jpanel_ventas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fresh_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fresh_cpuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fresh_cpuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_admin;
    private javax.swing.JPanel Jpanel_componentes;
    private javax.swing.JPanel Jpanel_perfiericos;
    private javax.swing.JPanel Jpanel_unidadc;
    private javax.swing.JPanel Jpanel_ventas;
    public javax.swing.JTable Jtable_cpu;
    public javax.swing.JTable Jtable_pf;
    public javax.swing.JTextArea Jtext_dtventa;
    public javax.swing.JButton btn_aggcpu;
    public javax.swing.JButton btn_aggpf;
    public javax.swing.JButton btn_buscaridcpu;
    public javax.swing.JButton btn_buscaridpf;
    public javax.swing.JButton btn_deletepf;
    public javax.swing.JButton btn_editarcpu;
    public javax.swing.JButton btn_editarpf;
    public javax.swing.JButton btn_fresh_cpu;
    public javax.swing.JButton btn_freshpf;
    public javax.swing.JButton btn_impf;
    public javax.swing.JButton btn_limpiar_txtpc;
    public javax.swing.JButton btn_pagar;
    public javax.swing.JButton btn_proc_venta;
    public javax.swing.JButton btn_remov_cpu;
    public javax.swing.JComboBox<String> cbx_discocpu;
    public javax.swing.JComboBox<String> cbx_tipocon_pf;
    public javax.swing.JComboBox<String> cbx_tipopf;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JTextArea jtext_dtcpu;
    public javax.swing.JTextArea jtext_dtpc;
    public javax.swing.JTextArea jtext_dtpf;
    public javax.swing.JLabel lbl_subtotfin;
    public javax.swing.JLabel lbl_total_compra;
    public javax.swing.JTextField txt_fabricpu;
    public javax.swing.JTextField txt_fabripf;
    public javax.swing.JTextField txt_idcpu;
    public javax.swing.JTextField txt_idcpu_pc;
    public javax.swing.JTextField txt_idpf;
    public javax.swing.JTextField txt_idpf_pc;
    public javax.swing.JTextField txt_modelocpu;
    public javax.swing.JTextField txt_modelopf;
    public javax.swing.JTextField txt_modiprecio;
    public javax.swing.JTextField txt_montopago;
    public javax.swing.JTextField txt_nomp;
    public javax.swing.JTextField txt_preciocpu;
    public javax.swing.JTextField txt_preciopf;
    public javax.swing.JTextField txt_proces_cpu;
    public javax.swing.JLabel txt_totalfin;
    // End of variables declaration//GEN-END:variables
}
